const KEYWORD_EMOJI: [string, string][] = [
  ['meeting', '🤝'],
  ['call', '📞'],
  ['email', '📧'],
  ['review', '👀'],
  ['write', '✍️'],
  ['writing', '✍️'],
  ['read', '📖'],
  ['reading', '📖'],
  ['design', '🎨'],
  ['code', '💻'],
  ['coding', '💻'],
  ['develop', '💻'],
  ['programming', '💻'],
  ['debug', '🐛'],
  ['bug', '🐛'],
  ['fix', '🔧'],
  ['test', '🧪'],
  ['testing', '🧪'],
  ['deploy', '🚀'],
  ['plan', '📋'],
  ['planning', '📋'],
  ['exercise', '💪'],
  ['gym', '💪'],
  ['workout', '💪'],
  ['run', '🏃'],
  ['running', '🏃'],
  ['lunch', '🍜'],
  ['dinner', '🍜'],
  ['breakfast', '🍜'],
  ['eat', '🍜'],
  ['food', '🍜'],
  ['coffee', '☕'],
  ['doctor', '🏥'],
  ['dentist', '🏥'],
  ['hospital', '🏥'],
  ['shop', '🛍️'],
  ['shopping', '🛍️'],
  ['buy', '🛍️'],
  ['clean', '🧹'],
  ['cleaning', '🧹'],
  ['research', '🔬'],
  ['study', '📚'],
  ['learn', '📚'],
  ['present', '🎤'],
  ['presentation', '🎤'],
  ['report', '📊'],
  ['analytics', '📊'],
  ['finance', '💰'],
  ['budget', '💰'],
  ['invoice', '💰'],
  ['pay', '💰'],
  ['travel', '✈️'],
  ['flight', '✈️'],
  ['hotel', '🏨'],
  ['document', '📄'],
  ['draft', '📝'],
  ['note', '📝'],
]

export function emojiFromTaskName(name: string): string {
  const lower = name.toLowerCase()
  for (const [keyword, emoji] of KEYWORD_EMOJI) {
    if (lower.includes(keyword)) return emoji
  }
  return '📋'
}
